# Generated by Django 4.1.3 on 2022-11-26 20:12

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset_State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('State', models.CharField(choices=[('New', 'New'), ('Like New', 'Used_Like New'), ('Good', 'Used_Good'), ('Fair', 'Used_Fair'), ('Damaged', 'Damaged')], default='N', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Asset_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dept_Name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_Name', models.CharField(default='CYPA', max_length=50)),
                ('Name', models.CharField(max_length=100)),
                ('Business', models.CharField(choices=[('Manufacturer', 'Manufacturer'), ('wholesaler', 'Wholesaler'), ('retailers', 'Retailer'), ('service and maintenance providers', 'Service and maintenance providers'), ('independent vendors', 'Independent vendors')], default='Manufacturer', max_length=40)),
                ('Address', models.TextField()),
                ('City', models.CharField(max_length=30)),
                ('Phone', models.CharField(max_length=15)),
                ('Email', models.EmailField(blank=True, max_length=50, null=True)),
                ('Website', models.URLField(blank=True, max_length=250, null=True)),
                ('Country', django_countries.fields.CountryField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=50)),
                ('Last_Name', models.CharField(max_length=40)),
                ('Title', models.TextField()),
                ('Phone', models.CharField(max_length=15)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Status', models.CharField(default='Active', max_length=10)),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.department')),
            ],
        ),
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Quantity', models.IntegerField()),
                ('Model', models.TextField()),
                ('Serian_Num', models.CharField(blank=True, max_length=100, null=True)),
                ('Date_Acquired', models.DateField()),
                ('Description', models.TextField()),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.department')),
                ('Employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.employees')),
                ('Location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.location')),
                ('State', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.asset_state')),
                ('Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.asset_type')),
                ('Vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.vendor')),
            ],
        ),
    ]
