# Generated by Django 3.1.14 on 2022-11-10 00:20

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset_State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('State', models.CharField(choices=[('N', 'New'), ('UN', 'Used_Like New'), ('UG', 'Used_Good'), ('UF', 'Used_Fair'), ('D', 'Damaged')], default='N', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Asset_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dept_Name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ven_Name', models.CharField(max_length=100)),
                ('Ven_Address', models.TextField()),
                ('Ven_City', models.TextField()),
                ('Ven_Phone', models.CharField(max_length=15)),
                ('Ven_Country', django_countries.fields.CountryField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=50)),
                ('Last_Name', models.CharField(max_length=40)),
                ('Title', models.TextField()),
                ('Phone', models.CharField(max_length=15)),
                ('Email', models.EmailField(max_length=254)),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.department')),
            ],
        ),
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Quantity', models.IntegerField()),
                ('Model', models.TextField()),
                ('Serian_Num', models.CharField(max_length=100)),
                ('Date_Acquired', models.DateField()),
                ('Description', models.TextField()),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.department')),
                ('Employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.employees')),
                ('Location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.location')),
                ('State', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.asset_state')),
                ('Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.asset_type')),
                ('Vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.vendor')),
            ],
        ),
    ]
