# Generated by Django 3.1.14 on 2022-11-10 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset_state',
            name='State',
            field=models.CharField(choices=[('New', 'New'), ('Like New', 'Used_Like New'), ('Good', 'Used_Good'), ('Fair', 'Used_Fair'), ('Damaged', 'Damaged')], default='N', max_length=15),
        ),
    ]
